# src/main/resources/application.yml
spring:
  application:
    name: aurumfi-blockchain
  main:
    banner-mode: off
    allow-bean-definition-overriding: true

server:
  port: 8082
  servlet:
    context-path: /

logging:
  level:
    com.aurumfi: DEBUG
    org.springframework: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"